language: rust
os:
  - linux
rust:
    - stable
    - beta
    - nightly
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libportmidi-dev
matrix:
    allow_failures:
        - rust: nightly
notifications:
    email:
        - thenyeguy@gmail.com
